export { Contact } from './Contact'
export { DesktopExperience } from './DesktopExperience'
export { DesktopWindow } from './DesktopWindow'
export { Projects } from './Projects'
export { Terminal } from './Terminal'
export { useWindowManager } from './useWindowManager'
export type { DesktopWindowState, SnapMode, WindowConfig, WindowId } from './types'
